name: Build and Test API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore .net-main/AccessControl.csproj

      - name: Build
        run: dotnet build .net-main/AccessControl.csproj --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test AccessControl.Tests/AccessControl.Tests.csproj --no-build --verbosity normal
